-- Replace DB_NAME and TABLE_NAME with database/table name
DROP DATABASE IF EXISTS `DB_NAME`;

CREATE DATABASE `DB_NAME`;

USE `DB_NAME`;

CREATE TABLE `TABLE_NAME` (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id)
);